### ISSUE TITLE
Request for RSS feed

### ISSUE THREAD

**Issue by koutheir** [hasheddan/danielmangum.com#253]
Can you please provide an RSS feed that allows following your blog posts?

**Comment by hasheddan** [comment]
@koutheir does https://danielmangum.com/index.xml work for you?

**Comment by koutheir** [comment]
Yes it seems to be working. Thank you!

**Comment by koutheir** [comment]
It might benefit other people to put a link on the web site.

**Comment by hasheddan** [comment]
@koutheir great idea! I'll add that :)

**Comment by hasheddan** [comment]
This was added to the home page at https://danielmangum.com/ -- thanks again for the suggestion!
